
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/FindGit.cmake:86 (find_program)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:1874 (find_package)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:1609 (__FetchContent_populateSubbuild)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:2145 (cmake_language)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)"
      - "CMakeLists.txt:14 (FetchContent_MakeAvailable)"
    mode: "program"
    variable: "GIT_EXECUTABLE"
    description: "Git command line client"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "git"
    candidate_directories:
      - "/home/ruvaak/.cargo/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/local/sbin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/var/lib/snapd/snap/bin/"
      - "/home/ruvaak/.local/bin/"
      - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux/"
    searched_directories:
      - "/home/ruvaak/.cargo/bin/git"
      - "/usr/local/bin/git"
    found: "/usr/bin/git"
    search_context:
      ENV{PATH}:
        - "/home/ruvaak/.cargo/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/local/sbin"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/var/lib/snapd/snap/bin"
        - "/home/ruvaak/.local/bin"
        - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux"
        - "/home/ruvaak/.cargo/bin"
        - "/home/ruvaak/.local/bin"

---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/FindGit.cmake:86 (find_program)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:1874 (find_package)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:1609 (__FetchContent_populateSubbuild)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:2145 (cmake_language)"
      - "/usr/share/cmake/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)"
      - "CMakeLists.txt:14 (FetchContent_MakeAvailable)"
    mode: "program"
    variable: "GIT_EXECUTABLE"
    description: "Git command line client"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "git"
    candidate_directories:
      - "/home/ruvaak/.cargo/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/local/sbin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/var/lib/snapd/snap/bin/"
      - "/home/ruvaak/.local/bin/"
      - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux/"
    searched_directories:
      - "/home/ruvaak/.cargo/bin/git"
      - "/usr/local/bin/git"
    found: "/usr/bin/git"
    search_context:
      ENV{PATH}:
        - "/home/ruvaak/.cargo/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/local/sbin"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/var/lib/snapd/snap/bin"
        - "/home/ruvaak/.local/bin"
        - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux"
        - "/home/ruvaak/.cargo/bin"
        - "/home/ruvaak/.local/bin"
