
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/ruvaak/.cargo/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/local/sbin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/var/lib/snapd/snap/bin/"
      - "/home/ruvaak/.local/bin/"
      - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux/"
    searched_directories:
      - "/home/ruvaak/.cargo/bin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/ruvaak/.cargo/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/local/sbin"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/var/lib/snapd/snap/bin"
        - "/home/ruvaak/.local/bin"
        - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux"
        - "/home/ruvaak/.cargo/bin"
        - "/home/ruvaak/.local/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.17.7-zen1-1-zen - x86_64
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/home/ruvaak/.cargo/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/local/sbin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/var/lib/snapd/snap/bin/"
      - "/home/ruvaak/.local/bin/"
      - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux/"
    searched_directories:
      - "/home/ruvaak/.cargo/bin/gmake"
      - "/usr/local/bin/gmake"
      - "/usr/bin/gmake"
      - "/bin/gmake"
      - "/usr/local/sbin/gmake"
      - "/var/lib/flatpak/exports/bin/gmake"
      - "/usr/lib/jvm/default/bin/gmake"
      - "/usr/bin/site_perl/gmake"
      - "/usr/bin/vendor_perl/gmake"
      - "/usr/bin/core_perl/gmake"
      - "/var/lib/snapd/snap/bin/gmake"
      - "/home/ruvaak/.local/bin/gmake"
      - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux/gmake"
      - "/home/ruvaak/.cargo/bin/make"
      - "/usr/local/bin/make"
    found: "/usr/bin/make"
    search_context:
      ENV{PATH}:
        - "/home/ruvaak/.cargo/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/local/sbin"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/var/lib/snapd/snap/bin"
        - "/home/ruvaak/.local/bin"
        - "/home/ruvaak/.cache/yay/texlive-full/pkg/texlive-full/opt/texlive/2024/bin/x86_64-linux"
        - "/home/ruvaak/.cargo/bin"
        - "/home/ruvaak/.local/bin"
...
